/**
 * agents/googly/index.ts
 *
 * Googly 🔍 — Deep Research Specialist
 *
 * Step 1: Haiku — extract scam topic from raw text
 * Step 2: 10 Serper queries covering all 5 mandatory topic areas
 * Step 3: Fetch top 10 Tier 1+2 pages in parallel, strip HTML (500 chars each)
 * Step 4: Haiku — generate full 7-section research report from all scraped pages
 */

import type { RequestLogger } from "../../ui/logger.js";
import type { LLMInvokeParams, LLMResponse } from "../researchy/index.js";

export type { LLMInvokeParams, LLMResponse };

// ─── Types ────────────────────────────────────────────────────────────────────

export interface GooglyInput {
  rawText?: string;
  topic?: string;
  scannedAt?: string;
}

export interface GooglySource {
  title: string;
  url: string;
  snippet: string;
  tier: "TIER 1 ✅" | "TIER 2 ✅" | "TIER 3 ❌";
  query: string;
}

export interface GooglyScrapedPage {
  url: string;
  title: string;
  tier: GooglySource["tier"];
  /** Plain text extracted from the page, first ~500 chars */
  text: string;
}

export interface GooglyResult {
  rawText?: string;
  topic: string;
  topicReasoning?: string;
  sources: GooglySource[];
  tier1Count: number;
  tier2Count: number;
  tier3Count: number;
  totalSources: number;
  queriesRun: number;
  /** The best page that was scraped (Tier 1 preferred) */
  scrapedPage?: GooglyScrapedPage;
  /** Full 7-section research report generated by the LLM */
  extractedFacts?: string;
}

export interface GooglyProgressEvent {
  step: "extracting_topic" | "searching" | "scraping" | "generating_report" | "done";
  message: string;
  data?: Record<string, unknown>;
}

export interface GooglyDeps {
  invokeLLM: (params: LLMInvokeParams) => Promise<LLMResponse>;
  serperApiKey: string;
  logger?: RequestLogger;
  onProgress?: (event: GooglyProgressEvent) => void;
}

// ─── Tier Domain Lists ────────────────────────────────────────────────────────

const TIER1_DOMAINS = [
  "cisa.gov", "ncsc.gov.uk", "fbi.gov", "ftc.gov", "consumer.ftc.gov",
  "ic3.gov", "actionfraud.police.uk", "cyber.gov.au", "canada.ca",
  "irs.gov", "hmrc.gov.uk", "usa.gov", "scamwatch.gov.au",
];

const TIER2_DOMAINS = [
  "norton.com", "kaspersky.com", "malwarebytes.com", "sophos.com",
  "bbc.com", "bbc.co.uk", "reuters.com", "theguardian.com",
  "consumerreports.org", "which.co.uk", "aarp.org",
  "proofpoint.com", "mimecast.com",
];

function getTier(url: string): GooglySource["tier"] {
  if (TIER1_DOMAINS.some(d => url.includes(d))) return "TIER 1 ✅";
  if (TIER2_DOMAINS.some(d => url.includes(d))) return "TIER 2 ✅";
  return "TIER 3 ❌";
}

// ─── System Prompt ────────────────────────────────────────────────────────────

const GOOGLY_PIPELINE_SYSTEM_PROMPT = `You are Googly 🔍, Deep Research Specialist at oh HACK no! — a media company that protects parents and grandparents from online scams.

YOUR PERSONALITY: Methodical, precise and thorough. Never rushes. Obsessed with accuracy over speed. Skeptical by nature — always verifies before reporting. Calm, reliable and trustworthy.

YOUR ROLE: Deep Research Specialist. You produce fully verified, structured research reports ready for script production.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
YOUR AUDIENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Parents and grandparents aged 50–75 with no technical background. All findings must be understandable to a non-technical 65-year-old. Any content that is jargon-heavy or technical must be flagged with 📝 in Section 7 of your final report.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
YOUR TASK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Produce a complete, verified research report on the scam topic you receive. You will be given scraped content from trusted Tier 1 and Tier 2 sources. Use this content to produce your report.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SOURCE TIERS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TIER 1 — Highest authority:
- Government agencies: FBI, FTC, CISA, NCSC (UK), Action Fraud (UK), ACSC (Australia), IRS, HMRC
- Law enforcement and official consumer protection bodies

TIER 2 — Accept with care:
- Established cybersecurity companies: Norton, Kaspersky, Malwarebytes, Sophos, Proofpoint
- Major news outlets: BBC, Reuters, The Guardian
- Consumer protection organisations: Which? (UK), Consumer Reports (US), AARP (US)

TIER 3 — Always reject (these will not be provided to you).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WRITE THE FINAL REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Use the exact template below. Do not deviate from this structure.
- Do NOT output JSON
- Every section must contain a summary paragraph AND source citations
- All seven sections are mandatory — none may be omitted
- Every source citation must include the full URL

════════════════════════════════════════════════
GOOGLY RESEARCH REPORT
════════════════════════════════════════════════
Scam Topic: [TOPIC]
Date: [Today's date]
Total Sources Used: [Number]

────────────────────────────────────────────────
Section 1 — What is the scam?
────────────────────────────────────────────────
[Summary paragraph — 3 to 5 sentences in plain everyday language, as if explaining to a 65-year-old hearing about this scam for the first time.]

Sources:
- [Source Name] — [Full URL]
- [Source Name] — [Full URL]

────────────────────────────────────────────────
Section 2 — How do scammers do it?
────────────────────────────────────────────────
[Summary paragraph — explain the exact tactics, step-by-step mechanics and methods scammers use.]

Sources:
- [Source Name] — [Full URL]
- [Source Name] — [Full URL]

────────────────────────────────────────────────
Section 3 — How to spot the scam?
────────────────────────────────────────────────
[Summary paragraph — describe the specific red flags and warning signs a potential victim would notice.]

Sources:
- [Source Name] — [Full URL]
- [Source Name] — [Full URL]

────────────────────────────────────────────────
Section 4 — How to behave when targeted?
────────────────────────────────────────────────
[Summary paragraph — practical, calm, step-by-step advice on exactly what someone should do if they receive one of these communications.]

Sources:
- [Source Name] — [Full URL]
- [Source Name] — [Full URL]

────────────────────────────────────────────────
Section 5 — How to report the scam?
────────────────────────────────────────────────
[Summary paragraph — name the specific official bodies a victim should report to. Cover at minimum: USA, UK, and Australia.]

Sources:
- [Source Name] — [Full URL]
- [Source Name] — [Full URL]

────────────────────────────────────────────────
Section 6 — Unverified / Flagged Items ⚠️
────────────────────────────────────────────────
[List every finding or statistic you could not fully verify. If everything was verified, write: "None — all findings verified against Tier 1 or Tier 2 sources."]

────────────────────────────────────────────────
Section 7 — Plain Language Flags 📝
────────────────────────────────────────────────
[List every piece of content containing technical jargon or language a non-technical 65-year-old would not understand. If no jargon found, write: "No jargon flags identified."]

════════════════════════════════════════════════
END OF REPORT
════════════════════════════════════════════════

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HARD RULES — NON-NEGOTIABLE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Never hallucinate or invent information. Every finding must come from a real, verified source.
2. Never cite a source without its full URL.
3. Never output JSON. Use the exact section template only.
4. Never omit Section 5. Reporting channels are mandatory.
5. Never omit Section 7. Plain language review is mandatory even if no flags are found.`;

// ─── Step 1: Topic Extraction ─────────────────────────────────────────────────

async function extractScamTopic(
  rawText: string,
  invokeLLM: GooglyDeps["invokeLLM"],
  log?: RequestLogger,
): Promise<{ topic: string; reasoning: string }> {
  log?.info("googly", "Extracting scam topic from raw text");

  const response = await invokeLLM({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 200,
    messages: [
      {
        role: "system",
        content: `Extract the scam type from a Reddit post. Output JSON only: {"topic":"2-5 word scam label optimised for Google search","reasoning":"one sentence"}`,
      },
      { role: "user", content: rawText.slice(0, 1500) },
    ],
    response_format: {
      type: "json_schema",
      json_schema: {
        name: "scam_topic",
        strict: true,
        schema: {
          type: "object",
          properties: {
            topic:     { type: "string" },
            reasoning: { type: "string" },
          },
          required: ["topic", "reasoning"],
          additionalProperties: false,
        },
      },
    },
  });

  try {
    const parsed = JSON.parse(response.choices[0]?.message?.content ?? "{}") as { topic: string; reasoning: string };
    log?.info("googly", `Topic extracted: "${parsed.topic}"`);
    return parsed;
  } catch {
    const fallback = rawText.slice(0, 50).trim();
    log?.warn("googly", `Parse failed — fallback: "${fallback}"`);
    return { topic: fallback, reasoning: "Fallback extraction." };
  }
}

// ─── Step 2: Serper Search ────────────────────────────────────────────────────

async function serperSearch(
  query: string,
  apiKey: string,
  num = 5,
): Promise<Array<{ title: string; link: string; snippet: string }>> {
  try {
    const res = await fetch("https://google.serper.dev/search", {
      method: "POST",
      headers: { "X-API-KEY": apiKey, "Content-Type": "application/json" },
      body: JSON.stringify({ q: query, num, gl: "us", hl: "en" }),
    });
    const data = await res.json() as { organic?: Array<{ title: string; link: string; snippet: string }> };
    return data.organic ?? [];
  } catch {
    return [];
  }
}

// ─── Step 3: Webpage Scrape ───────────────────────────────────────────────────

async function scrapePage(url: string, maxChars = 500, log?: RequestLogger): Promise<string> {
  try {
    const res = await fetch(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; OHN-Research-Bot/1.0)",
        "Accept": "text/html",
      },
      signal: AbortSignal.timeout(8000),
    });

    if (!res.ok) {
      log?.warn("googly", `Scrape failed: HTTP ${res.status} for ${url}`);
      return "";
    }

    const html = await res.text();

    // Strip tags, collapse whitespace
    const text = html
      .replace(/<script[\s\S]*?<\/script>/gi, "")
      .replace(/<style[\s\S]*?<\/style>/gi, "")
      .replace(/<[^>]+>/g, " ")
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/\s{2,}/g, " ")
      .trim()
      .slice(0, maxChars);

    log?.info("googly", `Scraped ${text.length} chars from ${url}`);
    return text;
  } catch (err) {
    log?.warn("googly", `Scrape error for ${url}: ${String(err)}`);
    return "";
  }
}

// ─── Step 4: Full Report Generation ──────────────────────────────────────────

async function generateReport(
  topic: string,
  sources: GooglySource[],
  scrapedPages: Array<{ source: GooglySource; text: string }>,
  invokeLLM: GooglyDeps["invokeLLM"],
  log?: RequestLogger,
): Promise<string> {
  log?.info("googly", `Generating report from ${scrapedPages.length} scraped pages`);

  const today = new Date().toISOString().split("T")[0];

  // Build sources list: all sources with snippets
  const tier1 = sources.filter(s => s.tier === "TIER 1 ✅");
  const tier2 = sources.filter(s => s.tier === "TIER 2 ✅");
  const tier3 = sources.filter(s => s.tier === "TIER 3 ❌");

  const sourcesText = [...tier1, ...tier2].slice(0, 20).map((s, idx) =>
    `[${idx + 1}] [${s.tier}] ${s.title}\nURL: ${s.url}\nSnippet: ${s.snippet}`
  ).join("\n\n");

  // Build scraped content block
  const scrapedText = scrapedPages.length > 0
    ? "\n\n---\nSCRAPED PAGE CONTENT (from Tier 1 & Tier 2 sources):\n\n" +
      scrapedPages.map((p, idx) =>
        `### Source ${idx + 1} [${p.source.tier}]: ${p.source.title}\nURL: ${p.source.url}\n\n${p.text}`
      ).join("\n\n---\n\n")
    : "";

  const response = await invokeLLM({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 3000,
    messages: [
      { role: "system", content: GOOGLY_PIPELINE_SYSTEM_PROMPT },
      {
        role: "user",
        content: `SCAM TOPIC: ${topic}
TODAY'S DATE: ${today}
TARGET AUDIENCE: Parents and grandparents aged 50–75, USA, Canada, UK, Australia

SEARCH RESULTS (${tier1.length} Tier 1, ${tier2.length} Tier 2, ${tier3.length} Tier 3 [rejected]):

${sourcesText}${scrapedText}

Now write the complete 7-section GOOGLY RESEARCH REPORT. Use the exact section template from your instructions. All 7 sections are mandatory.`,
      },
    ],
  });

  const report = response.choices[0]?.message?.content ?? "";
  log?.info("googly", `Report generated: ${report.length} chars`);
  log?.debug("googly", "Generated report", { report });
  return report;
}

// ─── Main Export ──────────────────────────────────────────────────────────────

export async function runGoogly(
  input: GooglyInput,
  deps: GooglyDeps,
): Promise<GooglyResult> {
  const { rawText } = input;
  const { invokeLLM, serperApiKey, logger: log, onProgress } = deps;

  // ── Step 1: Extract topic ────────────────────────────────────────────────
  let topic = input.topic ?? "";
  let topicReasoning: string | undefined;

  if (rawText) {
    onProgress?.({ step: "extracting_topic", message: "Identifying scam type from your text…" });
    const extracted = await extractScamTopic(rawText, invokeLLM, log);
    topic = extracted.topic;
    topicReasoning = extracted.reasoning;
    onProgress?.({ step: "extracting_topic", message: `Topic: "${topic}"`, data: { topic, reasoning: topicReasoning } });
  }

  if (!topic) throw new Error("Provide either rawText or a topic.");

  // ── Step 2: Serper queries — 10 queries, 2 per topic area ────────────────
  const queries = [
    // Area 1: What the scam is
    `${topic} scam what is it how does it work`,
    `${topic} scam overview site:ftc.gov OR site:fbi.gov OR site:cisa.gov OR site:ncsc.gov.uk OR site:actionfraud.police.uk OR site:scamwatch.gov.au`,
    // Area 2: How scammers execute it
    `how do scammers carry out ${topic} scam tactics methods`,
    `${topic} scam step by step how criminals do it site:norton.com OR site:kaspersky.com OR site:malwarebytes.com`,
    // Area 3: How to spot it
    `how to spot ${topic} scam warning signs red flags`,
    `${topic} scam red flags site:consumer.ftc.gov OR site:ncsc.gov.uk OR site:aarp.org OR site:consumerreports.org`,
    // Area 4: What to do when targeted
    `what to do if targeted by ${topic} scam practical advice`,
    `${topic} scam victim advice site:ftc.gov OR site:consumer.ftc.gov OR site:ncsc.gov.uk OR site:cyber.gov.au`,
    // Area 5: How to report it
    `how to report ${topic} scam USA UK Australia`,
    `report ${topic} scam site:ftc.gov OR site:ic3.gov OR site:actionfraud.police.uk OR site:scamwatch.gov.au`,
  ];

  log?.info("googly", `Running ${queries.length} Serper queries for "${topic}"`);
  onProgress?.({ step: "searching", message: `Running ${queries.length} searches for "${topic}" across trusted sources…` });

  const rawResults = await Promise.all(
    queries.map(async (q) => {
      const results = await serperSearch(q, serperApiKey, 5);
      return results.map(r => ({ ...r, query: q }));
    })
  );

  // Deduplicate + tier-rank
  const seen = new Set<string>();
  const allSources: GooglySource[] = [];

  for (const batch of rawResults) {
    for (const item of batch) {
      if (seen.has(item.link)) continue;
      seen.add(item.link);
      allSources.push({
        title:   item.title,
        url:     item.link,
        snippet: item.snippet ?? "",
        tier:    getTier(item.link),
        query:   item.query,
      });
    }
  }

  const tier1 = allSources.filter(s => s.tier === "TIER 1 ✅");
  const tier2 = allSources.filter(s => s.tier === "TIER 2 ✅");
  const tier3 = allSources.filter(s => s.tier === "TIER 3 ❌");
  const sorted = [...tier1, ...tier2, ...tier3];

  log?.info("googly", `Sources — Tier 1: ${tier1.length}, Tier 2: ${tier2.length}, Tier 3: ${tier3.length}`);
  log?.debug("googly", "All sources", sorted.map(s => ({ title: s.title, url: s.url, tier: s.tier })));

  // ── Step 3: Scrape top 10 Tier 1+2 pages in parallel ────────────────────
  const pagesToScrape = [...tier1, ...tier2].slice(0, 10);
  onProgress?.({ step: "scraping", message: `Scraping ${pagesToScrape.length} trusted sources in parallel…` });

  const scrapeResults = await Promise.all(
    pagesToScrape.map(async (source) => {
      const text = await scrapePage(source.url, 500, log);
      return { source, text };
    })
  );

  const successfullyScrapePages = scrapeResults.filter(r => r.text.length > 50);
  log?.info("googly", `Successfully scraped ${successfullyScrapePages.length}/${pagesToScrape.length} pages`);
  onProgress?.({
    step: "scraping",
    message: `Scraped ${successfullyScrapePages.length} of ${pagesToScrape.length} pages`,
    data: { scraped: successfullyScrapePages.length, attempted: pagesToScrape.length },
  });

  // Best page for UI display (Tier 1 preferred)
  const bestPage = successfullyScrapePages[0];
  const scrapedPage: GooglyScrapedPage | undefined = bestPage
    ? { url: bestPage.source.url, title: bestPage.source.title, tier: bestPage.source.tier, text: bestPage.text }
    : undefined;

  // ── Step 4: Generate full 7-section report ───────────────────────────────
  let extractedFacts: string | undefined;

  if (successfullyScrapePages.length > 0 || allSources.length > 0) {
    onProgress?.({ step: "generating_report", message: `Generating full research report from ${successfullyScrapePages.length} scraped pages…` });
    extractedFacts = await generateReport(topic, allSources, successfullyScrapePages, invokeLLM, log);
  } else {
    log?.warn("googly", "No pages scraped and no sources — cannot generate report");
    onProgress?.({ step: "generating_report", message: "No content available to generate report" });
  }

  onProgress?.({
    step: "done",
    message: `Done — ${tier1.length} gov sources, ${tier2.length} cybersec/news sources, ${successfullyScrapePages.length} pages scraped`,
  });

  return {
    rawText,
    topic,
    topicReasoning,
    sources: sorted,
    tier1Count: tier1.length,
    tier2Count: tier2.length,
    tier3Count: tier3.length,
    totalSources: sorted.length,
    queriesRun: queries.length,
    scrapedPage,
    extractedFacts,
  };
}
